project:
  type: website

website:
  title: "A neglected blog"
  navbar:
    right:
      - text: "About"
        href: https://damoncroberts.io
      - icon: github
        href: https://github.com/damoncharlesroberts
  page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2025 Damon Charles Roberts</span>
      <span class="faux-block"><br>All content licensed under {{< fa brands creative-commons >}} [NON-AI CC0 1.0 Universal](https://github.com/DamonCharlesRoberts/blog?tab=License-1-ov-file)</span>

format:
  html:
    theme: 
      light: ./assets/theme/light.css
      dark: ./assets/theme/dark.css
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    code-fold: true

execute:
  freeze: auto
