#on:
#  #schedule:
#    #- cron: '0 5 * * *'
#  push:
#    branches: 
#      - 'main'
#
#name: Quarto Publish
#jobs:
#  build-deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository
#        uses: actions/checkout@v4 
#      - name: Set up Quarto
#        uses: quarto-dev/quarto-actions/setup@v2
#      - name: Install Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#          cache: 'pip'
#      - name: Install jupyter
#        run: pip install jupyter
#      - name: Install Python dependencies
#        run: pip install -r requirements.txt
#      - name: Update linux packages
#        run: sudo apt-get update
#      - name: Install cURL Headers
#        run: sudo apt-get install libcurl4-openssl-dev
#      - name: Install R
#        uses: r-lib/actions/setup-r@v2
#      - name: Install R dependencies
#        uses: r-lib/actions/setup-renv@v2
#      - name: Publish to netlify
#        uses: quarto-dev/quarto-actions/publish@v2
#        with:
#          target: netlify
#          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
